<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RustDeskHop</AssemblyName>
    <RootNamespace>Simultria.RustDeskCompanion</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="settings.local.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
